### PR TITLE
Adds missing steps to installation instructions

### PR DESCRIPTION
**Pull request by iammikek**
some extra steps to help someone install the demo.

### CODE REVIEW

**Comment by sinnbeck** [comment]
Thanks. Well spotted. Hope it worked as expected otherwise :)

**Comment by iammikek** [comment]
@sinnbeck yes it did. thanks.

**Comment by iammikek** [comment]
@sinnbeck would you be able to tweak this PR so I can also include in Hacktoberfest fest?

Ineligible Repository
Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate. Alternatively, an individual PR can be opted-in with a maintainer adding the "hacktoberfest-accepted" label to the PR.

**Comment by sinnbeck** [comment]
Label added :)

**Pull request merged**
